var bandeiras=["us","fr","nl","de","us","ru","br","us","ca","se","es","us"];
var recurso = recgen;
var divsnoty="<div id='notyTemplate' style='display: none'><div><div class='noty_message'><div><i class='fa fa-check-circle ' style='color: #018418;'></i> <span class='notyFlag'></span> <span class='notyName yellow' style='font-weight: bold;'>%name%</span> generated <span class='notyMessage'></span> <span class='notyRes'>%res%</span>!</div><div class='noty_close'></div></div></div></div><div id='notyTemplateFail' style='display: none'><div><div class='noty_message'><div><i class='fa fa-exclamation-triangle' style='color: #f12b2b;'></i> <span class='notyName yellow' style='font-weight: bold;'>%name%</span>: Failed Verification</div><div class='noty_close'></div></div></div></div>";$("body").append(divsnoty);function random(min,max){return Math.floor(Math.random()*(max- min+ 1)+ min);}
function makeid(tamanho){var text="";var possible="abcdefghijklmnoprstuvwxyz";for(var i=0;i<tamanho;i++)
text+=possible.charAt(Math.floor(Math.random()*possible.length));return text;}
$(document).ready(function(){var enable_notifications=parseInt("1");$(document).ready(function(){$('.loadingScreen').fadeOut(500);stickyNote();});var skip_generate=parseInt("0");var min_noti_delay=parseInt("4000");var max_noti_delay=parseInt("10000");var min_noti_points=parseInt("0");var max_noti_points=parseInt("0");function stickyNote(){if(enable_notifications==0)return false;var count=1;var counter=0;var next=random(min_noti_delay,max_noti_delay);if($('#noty_bottomRight_layout_container li:not(.i-am-closing)').length>=1){$('#noty_bottomRight_layout_container li').addClass("i-am-closing");$.noty.closeAll();}
while(counter<count){counter++;var Name=makeid(random(1,2))+"****"+makeid(random(1,3));var fakeIP=random(1,999)+"."+random(1,999)+"."+random(1,999)+"."+random(1,999);var $template;if(random(1,10)==10){$template=$($('#notyTemplateFail').html());}
else{$template=$($('#notyTemplate').html());var msg=$template.find('.notyMessage').html();$template.find('.notyMessage').html(random(5000,9999));}
$template.find('.notyFlag').html("<img src='https://cdnjs.cloudflare.com/ajax/libs/DinaKit/1.2/css/images/flags/"+bandeiras[random(0,bandeiras.length-1)]+".png' />");$template.find('.notyName').text(Name);$template.find('.notyRes').text(recurso.r[random(0,recurso.r.length-1)]);var n=noty({layout:'bottomRight',type:'alert',theme:'relax',killer:false,text:'',template:$template.html(),animation:{open:'animated fadeInUp',close:'animated fadeOutRight',easing:'swing',},maxVisible:1});}
setTimeout(function(){stickyNote()},next);}
$.noty.defaults={layout:'topRight',theme:'defaultTheme',type:'alert',text:'',dismissQueue:true,template:'<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',animation:{open:{height:'toggle'},close:{height:'toggle'},easing:'swing',speed:200},timeout:500,force:false,modal:false,maxVisible:3,killer:true,closeWith:['click'],callback:{onShow:function(){},afterShow:function(){},onClose:function(){},afterClose:function(){},onCloseClick:function(){},},buttons:false};});
